import { sidebar } from "vuepress-theme-hope";

export const Sidebar = sidebar([
  {
    text: "Main Menu",
    icon: "/menu.svg",
    children: [
      "/",
      "/links/",
      "/qap/",
      "/about/",
    ]
  },
  {
    text: "Mathematics",
    icon: '/navicons/math.svg',
    prefix: "/Mathematics/",
    collapsible: true,
    children: [
      {
        text: "Linear Algebra",
        icon: "/sideicons/matrix.svg",
        prefix: "LinearAlgebra/",
        collapsible: true,
        children: [
          "RelativeConcepts",
          "RelativeCompute",
          "Norm",
          "特征分解",
          "奇异值分解",
          "Moore-Penrose伪逆",
          "「实例」主成分分析",
        ],
      },
      {
        text: "Probability Theory",
        icon: "/sideicons/probability.svg",
        prefix: "ProbabilityTheory/",
        collapsible: true,
        children: [
          "随机变量",
          "概率分布",
          "边缘概率",
          "条件概率及其链式法则",
          "独立性和条件独立性",
          "期望、方差和协方差",
          "常见概率分布",
          "常见函数及其性质",
          "贝叶斯规则",
          "连续性变量的技术细节",
          "信息论",
          "结构化概率模型",
        ],
      },
      "CongruenceExpression",
      "LipschitzContinuity",
      "Convex",
      "ConjugateFunction",
    ],
  },
  {
    text: "Aritficial Intelligence",
    icon: "/navicons/AI.svg",
    prefix: "/ArtificialIntelligence/",
    collapsible: true,
    children: [
        "AIOverview",
        "EnvInstall",
        {
          text: "Generative Adversarial Networks",
          icon: "/sideicons/ai.svg",
          prefix: "GAN/",
          collapsible: true,
          children: [
            "ElementaryCourse",
            "StandardGAN",
            "WGAN",
            "WGAN-gp",
            "WGAN-div",
            "EnlightenGAN",
            "LowLightMetrics",
            "FGAN",
          ],
        },
        "ISDN",
        "GPU",
    ],
  },
  {
    text: "Data Structures",
    icon: "/navicons/data_structure.svg",
    prefix: "/DataStructures/",
    collapsible: true,
    children: [
      "Basis",
      "LinearList",
      {
        text: "Stack",
        icon: "/sideicons/stack.svg",
        collapsible: true,
        children: [
          "StackBasedonSequentialLinearList",
          "StackBasedonSingleLinkedList",
        ],
      },
      "Queue",
      {
        text: "Tree",
        icon: "/sideicons/tree.svg",
        collapsible: true,
        prefix: "Tree/",
        children: [
          "BinaryTree",
          "2-3Tree",
          "Red-BlackTree",
          "BTree",
          "B-plusTree.md",
        ],
      },
    ],
  },
  {
    text: "Algorithm Design and Analysis",
    icon: "/navicons/algorithm.svg",
    prefix: "/AlgorithmDesignAndAnalysis/",
    collapsible: true,
    children: [
      "Basis",
    ],
  },
  {
    text: "DataBase",
    icon: "/navicons/database.svg",
    prefix: "/Database/",
    collapsible: true,
    children: [
      "DataBase",
      "RelationalAlgebra",
      "MySQL",
      "NormalForm",
      // "QueryOptimization",
      // "Trigger",
      // "DatabaseSafety",
    ],
  },
  {
    text: "Linux",
    icon: "/navicons/archlinux.svg",
    prefix: "/Linux/",
    collapsible: true,
    children: [
      "Manjaro安装与配置",
      "ZeroTier-One安装与使用",
      "记服务器搭建过程",
      "PrivateNetdiskBuilding",
      "ArcolinuxAndAwesomeWM",
      "AutoIAC",
      "Shells",
      "BuildingServer",
      "openGauss",
      "ShareConda",
      "UUA",
      "SystemSafety",
      "KeXieNetDisk",
      "ArchLinux",
    ],
  },
  {
    text: "Web",
    icon: "/navicons/web.svg",
    prefix: "/Web/",
    collapsible: true,
    children: [
      "HowtoForceCVWhenBanned",
      "Frontbackend",
      "SDN",
    ],
  },
  {
    text: "Blog",
    icon: "/navicons/blog.svg",
    prefix: "/BlogBuildingAndUsing/",
    collapsible: true,
    children: [
      "BlogBuilding",
      "Markdown语法杂记",
      "LaTeXforMd",
      "ChangeBlogTheme",
      "CreateNewFilebyShell",
    ],
  },
  {
    text: "Others",
    icon: "/navicons/others.svg",
    collapsible: true,
    children: [
      "Crawler",
      "Windows10快捷键大全",
      "VComputer",
      "Git_Commands",
    ]
  },
]);
